# Generated by Django 3.2 on 2024-08-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepart',
            name='details1',
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='details',
            field=models.JSONField(default=dict),
        ),
    ]
